
DROP TABLE IF EXISTS `blog_posts`;

CREATE TABLE `blog_posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL DEFAULT '',
  `owner_id` bigint(20) unsigned DEFAULT '0',
  `blog_id` int(11) unsigned DEFAULT '0',
  `dateadd` int(10) unsigned NOT NULL DEFAULT '0',
  `lastmodified` int(10) unsigned NOT NULL DEFAULT '0',
  `datepost` int(10) unsigned NOT NULL DEFAULT '0',
  `visible` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Определяет видимость. 1 - видим всем, 0 - видим только по ссылке, -1 не виден никому',
  `allow_comments` tinyint(1) NOT NULL DEFAULT '0',
  `comments` int(10) unsigned NOT NULL DEFAULT '0',
  `last_comment` int(10) unsigned NOT NULL DEFAULT '0',
  `last_comment_uid` int(10) unsigned NOT NULL DEFAULT '0',
  `thumb` varchar(255) NOT NULL DEFAULT '',
  `title` varchar(255) NOT NULL DEFAULT '',
  `preview` longtext NOT NULL,
  `text` longtext NOT NULL,
  `tags_cache` text NOT NULL,
  `have_cut` tinyint(1) NOT NULL DEFAULT '0',
  `views` int(10) unsigned NOT NULL DEFAULT '0',
  `rating` float NOT NULL DEFAULT '0',
  `ref_clicks` int(10) unsigned NOT NULL DEFAULT '0',
  `rating_total` int(11) NOT NULL DEFAULT '0',
  `rating_count` int(11) NOT NULL DEFAULT '0',
  `copyright_str` varchar(255) NOT NULL DEFAULT '',
  `source_url` varchar(255) NOT NULL DEFAULT '',
  `status` enum('posted','deferred','in_moderation','cancelled','deleted','day','draft') NOT NULL DEFAULT 'posted',
  `post_mode` enum('text','photo','video','import') NOT NULL DEFAULT 'text',
  `when_post` int(10) unsigned NOT NULL DEFAULT '0',
  `mainpic_id` int(10) unsigned DEFAULT NULL,
  `geo_lat` double NOT NULL DEFAULT '0',
  `geo_lng` double NOT NULL DEFAULT '0',
  `geo_address` varchar(255) NOT NULL DEFAULT '',
  `video_type` varchar(20) NOT NULL DEFAULT '',
  `video_id` varchar(50) NOT NULL DEFAULT '',
  `video_link` varchar(255) NOT NULL DEFAULT '',
  `pin_n` tinyint(3) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `visible` (`visible`),
  KEY `status` (`status`),
  KEY `last_comment` (`last_comment`),
  KEY `blog_id` (`blog_id`),
  KEY `comments` (`comments`,`status`),
  KEY `list_post` (`status`,`blog_id`,`datepost`),
  KEY `datepost` (`datepost`,`status`),
  KEY `random_pic` (`status`,`id`),
  KEY `pin_n` (`pin_n`),
  KEY `mainpic_id` (`mainpic_id`),
  KEY `FK_blog_posts_users` (`owner_id`),
  CONSTRAINT `FK_blog_posts_users` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_blogs_posts` FOREIGN KEY (`blog_id`) REFERENCES `blogs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_blog_posts` FOREIGN KEY (`mainpic_id`) REFERENCES `blog_images` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
