CREATE TABLE IF NOT EXISTS `pages` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `url` varchar(50) NOT NULL default '',
  `dateadd` int(10) unsigned NOT NULL default '0',
  `last_modified` int(10) unsigned NOT NULL default '0',
  `title` varchar(255) NOT NULL default '',
  `kws` varchar(255) NOT NULL default '',
  `description` varchar(255) NOT NULL default '',
  `text` LONGTEXT NOT NULL,
  `parent_id` int(11) NOT NULL default '0',
  `comments` int(11) NOT NULL default '0',
  `last_comment` int(11) NOT NULL default '0',
  `last_comment_uid` int(11) NOT NULL default '0',
  `allow_comment` int(11) NOT NULL default '0',
  `ordr` int(11) NOT NULL default '0',
  `show_in_menu` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `url` (`url`),
  KEY `parent_id` (`parent_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;